// Real screenshots of named page states, so layout is judged by eye and not by
// arithmetic. Chrome is driven through DevTools so below-fold #hash states are
// scrolled into view only after fonts and images have settled.
// Usage: node scripts/shoot.mjs story            (dev server on :5173)
//        node scripts/shoot.mjs all --base http://localhost:4173
import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const args = process.argv.slice(2);
const set = args.find((a) => !a.startsWith('--')) ?? 'all';
const base = args.includes('--base') ? args[args.indexOf('--base') + 1] : 'http://localhost:5173';

const STOPS = ['order', 'bill', 'load', 'send', 'remind', 'recover', 'tally'];
const SETS = {
  home: [['home-top', '/']],
  story: STOPS.map((id) => [`story-${id}`, `/#stop-${id}`]),
  hub: [['hub-top', '/features'], ['hub-sections', '/features#order'], ['hub-mid', '/features#send']],
  // Every feature page, because each one now carries its own screen and the
  // only way to know the right one landed is to look at all 27.
  feature: [
    ['feature-salesman-app-tally', '/salesman-app-tally'],
    ['feature-payment-collection-tally', '/payment-collection-tally'],
    ['feature-payment-reminder-tally', '/payment-reminder-tally'],
    ['feature-e-invoice-from-phone', '/e-invoice-from-phone'],
    ['feature-e-way-bill-from-phone', '/e-way-bill-from-phone'],
    ['feature-tally-reports-on-mobile', '/tally-reports-on-mobile'],
    ['feature-import-purchase-from-pdf', '/import-purchase-from-pdf'],
    ['feature-tally-on-mobile', '/tally-on-mobile'],
    ['feature-outstanding-receivables-on-mobile', '/outstanding-receivables-on-mobile'],
    ['feature-share-ledger-statement-whatsapp', '/share-ledger-statement-whatsapp'],
    ['feature-debtor-ageing-report-on-phone', '/debtor-ageing-report-on-phone'],
    ['feature-tally-on-mobile-without-remote-access', '/tally-on-mobile-without-remote-access'],
    ['feature-send-payment-reminders-automatically', '/send-payment-reminders-automatically'],
    ['feature-bank-statement-import-tally', '/bank-statement-import-tally'],
    ['feature-godown-wise-stock-on-mobile', '/godown-wise-stock-on-mobile'],
    ['feature-multi-company-tally-reports', '/multi-company-tally-reports'],
    ['feature-sales-order-on-mobile', '/sales-order-on-mobile'],
    ['feature-delivery-challan-from-mobile', '/delivery-challan-from-mobile'],
    ['feature-credit-note-from-phone', '/credit-note-from-phone'],
    ['feature-custom-invoice-template-tally', '/custom-invoice-template-tally'],
    ['feature-handwritten-order-to-tally', '/handwritten-order-to-tally'],
    ['feature-order-booking-app-tally', '/order-booking-app-tally'],
    ['feature-biz-analyst-alternative', '/biz-analyst-alternative'],
    ['feature-livekeeping-alternative', '/livekeeping-alternative'],
    ['feature-tally-app-for-fmcg-distributors', '/tally-app-for-fmcg-distributors'],
    ['feature-tally-app-for-pharma-distributors', '/tally-app-for-pharma-distributors'],
    ['feature-tally-app-for-agri-input-distributors', '/tally-app-for-agri-input-distributors'],
    ['feature-voucher-approval-before-tally', '/voucher-approval-before-tally'],
    ['feature-ai-collection-calls', '/ai-collection-calls'],
  ],
  sheets: [
    ['sheet-loading', '/?sheet=sheet-loading#stop-load'],
    ['sheet-salesman', '/?sheet=sheet-salesman#stop-tally'],
  ],
};
// The same 27 pages scrolled to their story section (walkthrough grid or
// tour), because the cards live below the fold and the hero shot never shows
// them. Layout's useScrollToHash lands on the section id.
SETS.walk = SETS.feature.map(([name, path]) => [
  name.replace(/^feature-/, 'walk-'),
  `${path}${path === '/salesman-app-tally' ? '#tour' : '#walkthrough'}`,
]);
// The in-detail cards on the three import pages (2026-09-20).
SETS.detail = ['import-purchase-from-pdf', 'bank-statement-import-tally', 'handwritten-order-to-tally'].map(
  (slug) => [`detail-${slug}`, `/${slug}#detail`]
);
// The exported sheet on the pages that carry one (2026-09-20).
SETS.sheet = [
  ['sheet-salesman-app-tally', '/salesman-app-tally#sheet'],
  ['sheet-delivery-challan-from-mobile', '/delivery-challan-from-mobile#sheet'],
];
// The reports page's gallery of every registered report screen (2026-09-20).
SETS.gallery = [['gallery-tally-reports-on-mobile', '/tally-reports-on-mobile#gallery']];
// The blog index and one post, because the header images are generated by a
// separate script and the only way to know they match the site is to look.
SETS.blog = [
  ['blog-index', '/blog', { until: '.blog-post-card-thumb img' }],
  ['blog-post', '/blog/accounts-receivable-automation'],
];
// The header's Features menu, opened (2026-09-20: it now lists all 29 pages).
// Two pages, because the nav repaints itself over a navy hero.
SETS.menu = [
  ['menu-home', '/', { click: '.nav-features-toggle' }],
  ['menu-hub', '/features', { click: '.nav-features-toggle' }],
];
// The two round-two pages and the hub sections they join (2026-09-20), so the
// day's check is six shots and not the whole 29-page feature set.
SETS.round2 = [
  ['round2-voucher-approval-before-tally', '/voucher-approval-before-tally'],
  ['round2-walk-voucher-approval-before-tally', '/voucher-approval-before-tally#walkthrough'],
  ['round2-hub-order', '/features#order'],
  ['round2-ai-collection-calls', '/ai-collection-calls'],
  ['round2-walk-ai-collection-calls', '/ai-collection-calls#walkthrough'],
  ['round2-hub-recover', '/features#recover'],
  ['round2-listen', '/ai-collection-calls#listen'],
  // The player mid-clip: paused it is grey bars, and the coloured half and the
  // moving waveform are the whole point of it.
  ['round2-listen-playing', '/ai-collection-calls#listen', { click: '.call-player-play' }],
];
// The states the 2026-09-21 phone fixes are of: the job row and the proof
// card's junction, the story intro, the phone menu, the connector band. Each is
// below the fold or behind a tap, so no hash lands on it; `scrollTo` puts the
// element at the top of the viewport after the page has settled.
SETS.mobile = [
  ['mobile-jobs', '/', { scrollTo: '.hv3-hero-jobs' }],
  ['mobile-story-intro', '/', { scrollTo: '.foi-intro' }],
  ['mobile-menu', '/', { click: '.mobile-menu-btn' }],
  ['mobile-book-call', '/', { click: '.mobile-menu-btn', then: '#mobile-menu .cta-btn--outline' }],
  ['mobile-tally', '/#tally'],
  ['mobile-about', '/about-us', { scrollTo: '.footer-bottom' }],
  ['mobile-about-cta', '/about-us', { scrollTo: '.company-page-cta' }],
  ['mobile-tour-steps', '/salesman-app-tally', { scrollTo: '.ftour-step:nth-of-type(2)' }],
];
SETS.all = [...SETS.home, ...SETS.story, ...SETS.hub, ...SETS.menu, ...SETS.feature, ...SETS.walk, ...SETS.detail, ...SETS.sheet, ...SETS.gallery, ...SETS.sheets];

if (!existsSync(CHROME)) throw new Error(`Chrome not found at ${CHROME}`);
if (!SETS[set]) throw new Error(`Unknown set "${set}". One of: ${Object.keys(SETS).join(', ')}`);
const outDir = resolve(root, 'shots', set);
mkdirSync(outDir, { recursive: true });

const sleep = (ms) => new Promise((done) => setTimeout(done, ms));
const profile = mkdtempSync(join(tmpdir(), 'takkada-shoot-'));
const chrome = spawn(CHROME, [
  '--headless=new', '--disable-gpu', '--hide-scrollbars', '--no-first-run',
  // A synthetic click is not a user gesture, so audio would refuse to start
  // and a player shot would always be the paused state.
  '--autoplay-policy=no-user-gesture-required',
  `--user-data-dir=${profile}`, '--remote-debugging-port=0', 'about:blank',
], { stdio: 'ignore' });

async function devtoolsPort() {
  const activePort = join(profile, 'DevToolsActivePort');
  for (let n = 0; n < 100; n += 1) {
    if (existsSync(activePort)) return readFileSync(activePort, 'utf8').split('\n')[0];
    await sleep(50);
  }
  throw new Error('Chrome DevTools port did not become ready');
}

async function cdp(wsUrl) {
  const ws = new WebSocket(wsUrl);
  await new Promise((resolveOpen, rejectOpen) => {
    ws.addEventListener('open', resolveOpen, { once: true });
    ws.addEventListener('error', rejectOpen, { once: true });
  });

  let id = 0;
  const pending = new Map();
  const events = new Map();
  ws.addEventListener('message', ({ data }) => {
    const message = JSON.parse(data);
    if (message.id) {
      const waiter = pending.get(message.id);
      pending.delete(message.id);
      if (message.error) waiter.reject(new Error(message.error.message));
      else waiter.resolve(message.result);
      return;
    }
    const queue = events.get(message.method);
    if (queue?.length) queue.shift()(message.params);
  });

  return {
    close: () => ws.close(),
    send(method, params = {}) {
      const messageId = ++id;
      return new Promise((resolveSend, rejectSend) => {
        pending.set(messageId, { resolve: resolveSend, reject: rejectSend });
        ws.send(JSON.stringify({ id: messageId, method, params }));
      });
    },
    event(method) {
      return new Promise((resolveEvent) => {
        if (!events.has(method)) events.set(method, []);
        events.get(method).push(resolveEvent);
      });
    },
  };
}

async function shoot(port, name, path, w, h, opts = {}) {
  const url = `${base}${path}`;
  const target = await fetch(`http://127.0.0.1:${port}/json/new?${encodeURIComponent('about:blank')}`, {
    method: 'PUT',
  }).then((response) => response.json());
  const client = await cdp(target.webSocketDebuggerUrl);
  try {
    await client.send('Page.enable');
    await client.send('Runtime.enable');
    await client.send('Emulation.setDeviceMetricsOverride', {
      width: w, height: h, deviceScaleFactor: 1, mobile: false,
    });
    const loaded = client.event('Page.loadEventFired');
    await client.send('Page.navigate', { url });
    await loaded;
    await client.send('Runtime.evaluate', {
      expression: 'document.fonts.ready',
      awaitPromise: true,
    });
    if (path.includes('#')) {
      const id = path.slice(path.indexOf('#') + 1);
      const result = await client.send('Runtime.evaluate', {
        expression: `new Promise((resolve) => {
          let attempts = 0;
          const scroll = () => {
            const el = document.getElementById(${JSON.stringify(id)});
            if (el) { el.scrollIntoView({ behavior: 'instant', block: 'start' }); resolve(true); }
            else if (attempts++ < 100) setTimeout(scroll, 50);
            else resolve(false);
          };
          scroll();
        })`,
        awaitPromise: true,
        returnByValue: true,
      });
      if (result.exceptionDetails || !result.result.value) throw new Error(`Could not scroll to #${id}`);
      await sleep(500);
    }
    // A route whose chunk arrives after the load event paints nothing for a
    // while, and 232 blog cards is the slowest of them. `until` waits for the
    // thing the shot is of, instead of guessing at a sleep.
    if (opts.until) {
      const found = await client.send('Runtime.evaluate', {
        expression: `new Promise((resolve) => {
          let attempts = 0;
          const look = () => {
            if (document.querySelector(${JSON.stringify(opts.until)})) resolve(true);
            else if (attempts++ < 150) setTimeout(look, 100);
            else resolve(false);
          };
          look();
        })`,
        awaitPromise: true,
        returnByValue: true,
      });
      if (!found.result.value) throw new Error(`${opts.until} never appeared on ${url}`);
    }

    // A menu that only exists while it is open cannot be proved by a shot of
    // the page it hangs off. `click` opens it first; a selector that is not on
    // the page at this width (the desktop nav below 900px) is not an error.
    if (opts.click) {
      // Retried: the first click can land before React has hydrated the
      // header, and a click on a not-yet-live button is silently nothing.
      // aria-expanded is the element's own account of whether it opened.
      const opened = await client.send('Runtime.evaluate', {
        expression: `new Promise((resolve) => {
          let rounds = 0;
          const tap = () => {
            const el = document.querySelector(${JSON.stringify(opts.click)});
            // aria-expanded for a disclosure, aria-pressed for a toggle: the
            // element's own account of whether the tap did anything.
            const on = el && (el.getAttribute('aria-expanded') === 'true'
              || el.getAttribute('aria-pressed') === 'true');
            if (on) { resolve('open'); return; }
            // A missing element is retried, not reported: at 390 the desktop
            // nav is display:none and never arrives, and on a server-rendered
            // route the button can be a hydration tick behind the load event.
            if (rounds++ >= 6) { resolve(el ? 'stuck' : 'absent'); return; }
            if (!el) { setTimeout(tap, 600); return; }
            // One click per round, then a wait long enough for React to
            // re-render the attribute. Clicking again before that read lands
            // toggles the menu shut while the stale attribute still says open.
            el.click();
            setTimeout(tap, 600);
          };
          tap();
        })`,
        awaitPromise: true,
        returnByValue: true,
      });
      if (opened.result.value === 'stuck') throw new Error(`${opts.click} never opened on ${url}`);
      await sleep(400);
      // A second tap inside what the first one opened (a menu action that
      // raises a modal). No aria to read back, so a plain click and a settle.
      if (opts.then) {
        const hit = await client.send('Runtime.evaluate', {
          expression: `(() => { const el = document.querySelector(${JSON.stringify(opts.then)}); if (el) el.click(); return !!el; })()`,
          returnByValue: true,
        });
        if (!hit.result.value) throw new Error(`${opts.then} not found on ${url}`);
        await sleep(500);
      }
    }
    if (opts.scrollTo) {
      const found = await client.send('Runtime.evaluate', {
        expression: `new Promise((resolve) => {
          let attempts = 0;
          const scroll = () => {
            const el = document.querySelector(${JSON.stringify(opts.scrollTo)});
            if (el) { el.scrollIntoView({ behavior: 'instant', block: 'start' }); resolve(true); }
            else if (attempts++ < 100) setTimeout(scroll, 50);
            else resolve(false);
          };
          scroll();
        })`,
        awaitPromise: true,
        returnByValue: true,
      });
      if (!found.result.value) throw new Error(`${opts.scrollTo} never appeared on ${url}`);
      await sleep(500);
    }
    await client.send('Runtime.evaluate', {
      expression: `Promise.race([
        Promise.all([...document.images].map((img) => {
          img.loading = 'eager';
          return img.decode().catch(() => {});
        })),
        new Promise((resolve) => setTimeout(resolve, 5000)),
      ])`,
      awaitPromise: true,
    });
    // decode() means the bitmap is ready, NOT that the compositor has rastered
    // the layer it goes in. captureScreenshot({fromSurface:true}) reads the
    // surface, so without this a hero image that decoded a frame too late came
    // out as bare background - and did it deterministically, which is what made
    // it look like a page bug. Two frames past the decode, then a settle.
    await client.send('Runtime.evaluate', {
      expression: `new Promise((resolve) =>
        requestAnimationFrame(() => requestAnimationFrame(resolve))
      )`,
      awaitPromise: true,
    });
    await sleep(400);
    const { data } = await client.send('Page.captureScreenshot', {
      format: 'png', fromSurface: true, captureBeyondViewport: false,
    });
    const out = resolve(outDir, `${name}-${w}.png`);
    rmSync(out, { force: true });
    writeFileSync(out, Buffer.from(data, 'base64'));
    console.log(out);
  } finally {
    client.close();
    await fetch(`http://127.0.0.1:${port}/json/close/${target.id}`);
  }
}

try {
  const port = await devtoolsPort();
  for (const [name, path, opts] of SETS[set]) {
    for (const [w, h] of [[1440, 900], [390, 844]]) await shoot(port, name, path, w, h, opts);
  }
} finally {
  if (chrome.exitCode === null) {
    const exited = new Promise((resolveExit) => chrome.once('exit', resolveExit));
    chrome.kill('SIGKILL');
    await exited;
  }
  rmSync(profile, { recursive: true, force: true, maxRetries: 10, retryDelay: 50 });
}
