import { ViteReactSSG } from 'vite-react-ssg';
import { routes } from './routes';
// First, so the @font-face rules are declared before any rule references them.
// Generated by scripts/vendorFonts.mjs — see CLAUDE.md §7 before touching fonts.
import './fonts.css';
import './styles.css';
import './premium.css';
import './home.css';
import './feature-page.css';
import './styles/wuxia-quotes.css';

export const createRoot = ViteReactSSG(
  { routes },
  ({ isClient }) => {
    if (isClient) {
      document.documentElement.classList.add('js');
    }
  }
);
